### ISSUE TITLE
Follow the steps.  test\demo\bin does not have any files.

### ISSUE THREAD

**Issue by PoisonousGame** [dazKind/hxgodot-cpp#14]
HP@DESKTOP-0OJGV60 MINGW64 ~/Documents/hxgodot-cpp (main)
$ make debug
haxe build-gen.hxml
Generating binding classes for Godot (float_64)...
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Nil
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: bool
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: int
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: float
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: String
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Vector2
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Vector2i
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Rect2
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Rect2i
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Vector3
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Vector3i
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Transform2D
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Plane
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Quaternion
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: AABB
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Basis
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Transform3D
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Color
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: StringName
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: NodePath
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: RID
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Callable
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Signal
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Dictionary
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedByteArray
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedInt32Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedInt64Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedFloat32Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedFloat64Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedStringArray
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedVector2Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedVector3Array
src/godot/macros/ClassGenMacros.hx:77: // builtins
src/godot/macros/ClassGenMacros.hx:78: PackedColorArray
mkdir -p test/demo/bin
haxe build-lib.hxml -debug
src/godot/macros/Macros.hx:154: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:155: // Class: example.testPackage.HxOtherInPackage
src/godot/macros/Macros.hx:491: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:492: // Virtuals
src/godot/macros/Macros.hx:493: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:154: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:155: // Class: example.HxOther
src/godot/macros/Macros.hx:491: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:492: // Virtuals
src/godot/macros/Macros.hx:493: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:154: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:155: // Class: example.HxExample
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: set_hx_ImportantFloat
src/godot/macros/Macros.hx:254: {ret: TPath({name: Float, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:16: lines 16-58), expr: EBlock([{pos: #pos(src/example/HxExample.hx:18: characters 9-50), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:19: characters 9-58), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:22: characters 9-43), expr: EVars(<...>)},{pos: #pos(src/example/HxExample.hx:23: characters 9-17), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:24: characters 9-19), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:25: characters 9-19), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:26: characters 9-19), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:28: characters 9-40), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:29: characters 9-39), expr: EBinop(<...>,<...>,<...>)},{pos: #pos(src/example/HxExample.hx:30: characters 9-17), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:31: characters 9-19), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:32: characters 9-20), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:33: characters 9-41), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:34: characters 9-19), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:35: characters 9-19), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:38: characters 9-34), expr: EVars(<...>)},{pos: #pos(src/example/HxExample.hx:39: characters 9-37), expr: EVars(<...>)},{pos: #pos(src/example/HxExample.hx:40: characters 9-27), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:41: characters 9-33), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:42: characters 9-27), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:44: lines 44-45), expr: EFor(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:48: characters 9-47), expr: EVars(<...>)},{pos: #pos(src/example/HxExample.hx:49: characters 9-25), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:50: characters 9-28), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:52: lines 52-54), expr: EFor(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:56: characters 9-31), expr: EBinop(<...>,<...>,<...>)},{pos: #pos(src/example/HxExample.hx:57: characters 9-18), expr: EReturn(<...>)}])}, args: [{name: _v, opt: false, meta: [], type: TPath({name: Float, params: [], pos: #pos((unknown)), pack: []}), name_pos: #pos(src/example/HxExample.hx:16: characters 36-38), value: null}]}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: get_hx_ImportantFloat
src/godot/macros/Macros.hx:254: {ret: TPath({name: Float, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:61: lines 61-63), expr: EBlock([{pos: #pos(src/example/HxExample.hx:62: characters 9-33), expr: EReturn(<...>)}])}, args: []}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: set_hx_ImportantString
src/godot/macros/Macros.hx:254: {ret: TPath({name: GDString, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:72: lines 72-77), expr: EBlock([{pos: #pos(src/example/HxExample.hx:73: characters 9-42), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:74: characters 9-60), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:75: characters 9-32), expr: EBinop(<...>,<...>,<...>)},{pos: #pos(src/example/HxExample.hx:76: characters 9-18), expr: EReturn(<...>)}])}, args: [{name: _v, opt: false, meta: [], type: TPath({name: GDString, params: [], pos: #pos((unknown)), pack: []}), name_pos: #pos(src/example/HxExample.hx:72: characters 37-39), value: null}]}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: get_hx_ImportantString
src/godot/macros/Macros.hx:254: {ret: TPath({name: GDString, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:80: lines 80-82), expr: EBlock([{pos: #pos(src/example/HxExample.hx:81: characters 9-34), expr: EReturn(<...>)}])}, args: []}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: set_hx_random_MyVector3
src/godot/macros/Macros.hx:254: {ret: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:92: lines 92-95), expr: EBlock([{pos: #pos(src/example/HxExample.hx:93: characters 9-33), expr: EBinop(<...>,<...>,<...>)},{pos: #pos(src/example/HxExample.hx:94: characters 9-18), expr: EReturn(<...>)}])}, args: [{name: _v, opt: false, meta: [], type: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: []}), name_pos: #pos(src/example/HxExample.hx:92: characters 38-40), value: null}]}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: get_hx_random_MyVector3
src/godot/macros/Macros.hx:254: {ret: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:98: lines 98-100), expr: EBlock([{pos: #pos(src/example/HxExample.hx:99: characters 9-35), expr: EReturn(<...>)}])}, args: []}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: simple_func
src/godot/macros/Macros.hx:254: {ret: TPath({name: Bool, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:120: lines 120-123), expr: EBlock([{pos: #pos(src/example/HxExample.hx:121: characters 9-36), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:122: characters 9-20), expr: EReturn(<...>)}])}, args: []}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: simple_add
src/godot/macros/Macros.hx:254: {ret: TPath({name: Float, params: [], pos: #pos((unknown)), pack: []}), params: [], expr: {pos: #pos(src/example/HxExample.hx:126: lines 126-129), expr: EBlock([{pos: #pos(src/example/HxExample.hx:127: characters 9-54), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:128: characters 9-23), expr: EReturn(<...>)}])}, args: [{name: _a, opt: false, meta: [], type: TPath({name: Int, params: [], pos: #pos((unknown)), pack: []}), name_pos: #pos(src/example/HxExample.hx:126: characters 32-34), value: null},{name: _b, opt: false, meta: [], type: TPath({name: Float, params: [], pos: #pos((unknown)), pack: []}), name_pos: #pos(src/example/HxExample.hx:126: characters 40-42), value: null},{name: _bool, opt: false, meta: [], type: TPath({name: Bool, params: [], pos: #pos((unknown)), pack: []}), name_pos: #pos(src/example/HxExample.hx:126: characters 50-55), value: null}]}
src/godot/macros/Macros.hx:240: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:241: // FFun: simple_add_vector3
src/godot/macros/Macros.hx:254: {ret: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: [godot,variant]}), params: [], expr: {pos: #pos(src/example/HxExample.hx:137: lines 137-140), expr: EBlock([{pos: #pos(src/example/HxExample.hx:138: characters 9-56), expr: ECall(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:139: characters 9-25), expr: EReturn(<...>)}])}, args: [{name: _v0, opt: false, meta: [], type: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: [<...>,<...>]}), name_pos: #pos(src/example/HxExample.hx:137: characters 40-43), value: null},{name: _v1, opt: false, meta: [], type: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: [<...>,<...>]}), name_pos: #pos(src/example/HxExample.hx:137: characters 67-70), value: null}]}
src/godot/macros/Macros.hx:406: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:407: // FProp: hx_ImportantFloat
src/godot/macros/Macros.hx:408: {name: hx_ImportantFloat, doc: null, pos: #pos(src/example/HxExample.hx:13: characters 5-55), access: [APublic], kind: FProp(get,set,TPath({name: Float, params: [], pos: #pos((unknown)), pack: []}),{pos: #pos(src/example/HxExample.hx:13: characters 52-54), expr: EConst(CInt(22))}), meta: [{name: :isVar, params: [], pos: #pos(src/example/HxExample.hx:9: characters 5-12)},{name: :export, params: [], pos: #pos(src/example/HxExample.hx:10: characters 5-13)},{name: :hint, params: [{pos: #pos(src/example/HxExample.hx:11: characters 12-32), expr: EField(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:11: characters 34-45), expr: EConst(<...>)}], pos: #pos(src/example/HxExample.hx:11: characters 5-11)},{name: :group, params: [{pos: #pos(src/example/HxExample.hx:12: characters 13-33), expr: EConst(<...>)},{pos: #pos(src/example/HxExample.hx:12: characters 35-40), expr: EConst(<...>)}], pos: #pos(src/example/HxExample.hx:12: characters 5-12)}], name_pos: #pos(src/example/HxExample.hx:13: characters 16-33)}
src/godot/macros/Macros.hx:409: get
src/godot/macros/Macros.hx:410: set
src/godot/macros/Macros.hx:411: TPath({name: Float, params: [], pos: #pos((unknown)), pack: []})
src/godot/macros/Macros.hx:406: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:407: // FProp: hx_ImportantString
src/godot/macros/Macros.hx:408: {name: hx_ImportantString, doc: null, pos: #pos(src/example/HxExample.hx:69: characters 5-79), access: [APublic], kind: FProp(get,set,TPath({name: GDString, params: [], pos: #pos((unknown)), pack: []}),{pos: #pos(src/example/HxExample.hx:69: characters 56-78), expr: EConst(CString(Initial String Value,DoubleQuotes))}), meta: [{name: :isVar, params: [], pos: #pos(src/example/HxExample.hx:66: characters 5-12)},{name: :export, params: [], pos: #pos(src/example/HxExample.hx:67: characters 5-13)},{name: :hint, params: [{pos: #pos(src/example/HxExample.hx:68: characters 12-41), expr: EField(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:68: characters 43-45), expr: EConst(<...>)}], pos: #pos(src/example/HxExample.hx:68: characters 5-11)}], name_pos: #pos(src/example/HxExample.hx:69: characters 16-34)}
src/godot/macros/Macros.hx:409: get
src/godot/macros/Macros.hx:410: set
src/godot/macros/Macros.hx:411: TPath({name: GDString, params: [], pos: #pos((unknown)), pack: []})
src/godot/macros/Macros.hx:406: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:407: // FProp: hx_random_MyVector3
src/godot/macros/Macros.hx:408: {name: hx_random_MyVector3, doc: null, pos: #pos(src/example/HxExample.hx:89: characters 5-75), access: [APublic], kind: FProp(get,set,TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: []}),{pos: #pos(src/example/HxExample.hx:89: characters 56-74), expr: ENew({name: Vector3, params: [], pos: #pos(src/example/HxExample.hx:89: characters 60-67), pack: []},[{pos: <...>, expr: <...>},{pos: <...>, expr: <...>},{pos: <...>, expr: <...>}])}), meta: [{name: :isVar, params: [], pos: #pos(src/example/HxExample.hx:85: characters 5-12)},{name: :export, params: [], pos: #pos(src/example/HxExample.hx:86: characters 5-13)},{name: :hint, params: [{pos: #pos(src/example/HxExample.hx:87: characters 12-31), expr: EField(<...>,<...>)},{pos: #pos(src/example/HxExample.hx:87: characters 33-43), expr: EConst(<...>)}], pos: #pos(src/example/HxExample.hx:87: characters 5-11)},{name: :subGroup, params: [{pos: #pos(src/example/HxExample.hx:88: characters 16-35), expr: EConst(<...>)},{pos: #pos(src/example/HxExample.hx:88: characters 37-48), expr: EConst(<...>)}], pos: #pos(src/example/HxExample.hx:88: characters 5-15)}], name_pos: #pos(src/example/HxExample.hx:89: characters 16-35)}
src/godot/macros/Macros.hx:409: get
src/godot/macros/Macros.hx:410: set
src/godot/macros/Macros.hx:411: TPath({name: Vector3, params: [], pos: #pos((unknown)), pack: []})
src/godot/macros/Macros.hx:491: ////////////////////////////////////////////////////////////////////////////////
src/godot/macros/Macros.hx:492: // Virtuals
src/godot/macros/Macros.hx:493: ////////////////////////////////////////////////////////////////////////////////
haxelib run hxcpp Build.xml haxe -Ddebug -DHXCPP_CPP11="1" -DHXCPP_M64="1" -Dcompiletime="2.8.0" -Ddll_link="1" -Dhaxe="4.2.5" -Dhaxe3="1" -Dhaxe4="1" -Dhaxe_ver="4.205" -Dhxcpp_api_level="400" -Dhxcpp_smart_strings="1" -Dsource_header="Generated by Haxe 4.2.5" -Dstatic="1" -Dtarget.name="cpp" -Dtarget.static="true" -Dtarget.sys="true" -Dtarget.threaded="true" -Dtarget.unicode="true" -Dtarget.utf16="true" -Dutf16="1" -I"C:\\HaxeToolkit\\haxe\\lib\\compiletime/2,8,0/src/" -I"src/" -I"gen/" -I"" -I"C:\\HaxeToolkit\\haxe\\extraLibs/" -I"C:\\HaxeToolkit\\haxe\\std/cpp/_std/" -I"C:\\HaxeToolkit\\haxe\\std/"

**Comment by dazKind** [comment]
The setup process no longer works this way. Closing this particular issue
